name: Build analysis-pipeline on tag

on:
  push:
    tags:
      - "analysis-pipeline-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install -U pip build
      - name: Build sdist/wheel
        working-directory: software/analysis-pipeline
        run: python -m build
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            software/analysis-pipeline/dist/*.whl
            software/analysis-pipeline/dist/*.tar.gz
