name: CI (data)
on:
  pull_request: { paths: ['data/**','scripts/validate_manifest.py'] }
  push:         { paths: ['data/**'] }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install jsonschema
      - run: for f in data/manifests/*.json; do python scripts/validate_manifest.py "$f"; done
