name: Data manifest check
on:
  push:
    paths: ['data/**', 'scripts/validate_manifest.py', '.github/workflows/ci-data.yml']
  pull_request:
    paths: ['data/**', 'scripts/validate_manifest.py', '.github/workflows/ci-data.yml']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install -U pip jsonschema
      - run: |
          for f in data/manifests/*.json; do
            python scripts/validate_manifest.py "$f";
          done
